### ISSUE TITLE
Missing Kernel Quirk

### ISSUE THREAD

**Issue by 5T33Z0** [luchina-gabriel/BASE-EFI-INTEL-DESKTOP-3RDGEN-IVY-BRIDGE#1]
Hi. Great work on all the EFI Folders. I had a look into the Ivy Bridge Config and noticed that 

**AppleCpumPmCfgLock** 

is not enabled. But this mandatory to boot macOS unless you can deactiviate CFGLock in BIOS. 

Greetings.

BTW I linked to your configs in my OC-Little Repo: https://github.com/5T33Z0/OC-Little-Translated/tree/main/F_Desktop_EFIs

**Comment by luchina-gabriel** [comment]
Hi ;)

This parameter has a special note in README.md file.

Only be enabled with mobos that don't have a CFG Lock configuration support.

Thanks for your feedback e and thanks for sharing that work ;)

Regards,
Gabriel
